//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirtelSalesDBEntities : DbContext
    {
        public AirtelSalesDBEntities()
            : base("name=AirtelSalesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<all_survey_questions> all_survey_questions { get; set; }
        public virtual DbSet<all_survey_responses> all_survey_responses { get; set; }
        public virtual DbSet<all_surveys> all_surveys { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<IncentiveConfig> IncentiveConfigs { get; set; }
        public virtual DbSet<kpi_area_sales> kpi_area_sales { get; set; }
        public virtual DbSet<kpi_mktdev_sales> kpi_mktdev_sales { get; set; }
        public virtual DbSet<kpi_region_sales> kpi_region_sales { get; set; }
        public virtual DbSet<kpi_zone_sales> kpi_zone_sales { get; set; }
        public virtual DbSet<sales_regions> sales_regions { get; set; }
        public virtual DbSet<survey_types> survey_types { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<kpi_agent_sales> kpi_agent_sales { get; set; }
        public virtual DbSet<kpi_dealer_sales> kpi_dealer_sales { get; set; }
        public virtual DbSet<kpi_reseller_sales> kpi_reseller_sales { get; set; }
        public virtual DbSet<kpi_subdealer_sales> kpi_subdealer_sales { get; set; }
        public virtual DbSet<sales_areas> sales_areas { get; set; }
        public virtual DbSet<sales_zones> sales_zones { get; set; }
        public virtual DbSet<sf_permissions> sf_permissions { get; set; }
        public virtual DbSet<sf_roles_perm_xref> sf_roles_perm_xref { get; set; }
        public virtual DbSet<sf_user_profiles> sf_user_profiles { get; set; }
        public virtual DbSet<sf_user_roles> sf_user_roles { get; set; }
        public virtual DbSet<z_donotousse_zonekpi> z_donotousse_zonekpi { get; set; }
        public virtual DbSet<z_donotoussez_kpi_reseller> z_donotoussez_kpi_reseller { get; set; }
        public virtual DbSet<z_donotoussez_kpiarea> z_donotoussez_kpiarea { get; set; }
        public virtual DbSet<z_donotoussez_kpidealer> z_donotoussez_kpidealer { get; set; }
        public virtual DbSet<z_donotoussez_kpimarketdev> z_donotoussez_kpimarketdev { get; set; }
        public virtual DbSet<z_donotoussez_kpisubdealer> z_donotoussez_kpisubdealer { get; set; }
    }
}
