//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_surveys
    {
        public int Id { get; set; }
        public int SurveyTypeId { get; set; }
        public string SurveyName { get; set; }
        public System.DateTime SurveryStartDate { get; set; }
        public System.DateTime SurveryExpiryDate { get; set; }
        public int SurveyStatus { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public int response_count { get; set; }
    
        public virtual survey_types survey_types { get; set; }
    }
}
