//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_survey_responses
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public int SurveryQuestionId { get; set; }
        public string SurveyAnswer { get; set; }
        public string agentcode { get; set; }
        public System.DateTime submission_date { get; set; }
        public string geo_longitude { get; set; }
        public string geo_latitude { get; set; }
        public int location_id { get; set; }
        public int state_id { get; set; }
        public int region_id { get; set; }
    }
}
