//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncentiveConfig
    {
        public string quarter { get; set; }
        public Nullable<decimal> orsc { get; set; }
        public Nullable<decimal> bts { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public int id { get; set; }
    }
}
