//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_agent_sales
    {
        public int Id { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string ResellerCode { get; set; }
        public int target_activation { get; set; }
        public int target_activebase { get; set; }
        public int target_recharge { get; set; }
        public decimal target_usage { get; set; }
        public Nullable<decimal> indirect_contribution { get; set; }
        public Nullable<decimal> distribution_pct1 { get; set; }
        public Nullable<decimal> distribution_pct2 { get; set; }
        public Nullable<long> actual_activation { get; set; }
        public Nullable<long> actual_activebase { get; set; }
        public Nullable<long> actual_recharge { get; set; }
        public Nullable<decimal> actual_usage { get; set; }
        public string ref_period { get; set; }
        public Nullable<long> orsc_comm { get; set; }
        public Nullable<long> bts_comm { get; set; }
    }
}
