//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi_mktdev_sales
    {
        public int Id { get; set; }
        public string MarketDevCode { get; set; }
        public string MarketDevName { get; set; }
        public string AreaCode { get; set; }
        public int target_activation { get; set; }
        public int target_activebase { get; set; }
        public int target_recharge { get; set; }
        public decimal target_usage { get; set; }
        public Nullable<decimal> distribution_pct { get; set; }
        public Nullable<long> actual_activation { get; set; }
        public Nullable<long> actual_activebase { get; set; }
        public Nullable<long> actual_recharge { get; set; }
        public Nullable<decimal> actual_usage { get; set; }
        public string ref_period { get; set; }
    }
}
