//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_permissions
    {
        public int PERMISSION_ID { get; set; }
        public string PERMISSIONDESCRIPTION { get; set; }
        public string ACTION_NAME { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public int PARENT_PERMISSION { get; set; }
        public string FORM_URL { get; set; }
        public string IMAGE_URL { get; set; }
        public bool ISACTIVE { get; set; }
        public string ICON_CLASS { get; set; }
        public string ISOPEN_CLASS { get; set; }
        public string TOGGLE_ICON { get; set; }
    }
}
