//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_user_profiles
    {
        public int PROFILE_ID { get; set; }
        public string USER_ID { get; set; }
        public string COD_PASSWORD { get; set; }
        public string PASSWORDSALT { get; set; }
        public string PASSWORDQUESTION { get; set; }
        public string PASSWORDANSWER { get; set; }
        public Nullable<bool> ISAPPROVED { get; set; }
        public bool ISLOCKED { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> LASTLOGINDATE { get; set; }
        public Nullable<System.DateTime> LASTPASSWORDCHANGEDDATE { get; set; }
        public Nullable<System.DateTime> LASTLOCKOUTDATE { get; set; }
        public Nullable<int> FAILEDPASSWORDATTEMPTCOUNT { get; set; }
        public Nullable<bool> FLAG_ALLOW_DOC_SHARING { get; set; }
        public Nullable<bool> FLAG_ALLOW_SMS_ALERT { get; set; }
        public int ROLE_ID { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string BRANCH_ID { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
        public string region_code { get; set; }
        public string zonal_code { get; set; }
        public string area_code { get; set; }
        public string marketdev_code { get; set; }
        public string dealer_code { get; set; }
        public string subdealer_code { get; set; }
        public string reseller_code { get; set; }
        public string agent_code { get; set; }
    }
}
