//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_donotoussez_kpiarea
    {
        public int Id { get; set; }
        public string Area_Code { get; set; }
        public string Area_Name { get; set; }
        public string Zone_Code { get; set; }
        public string Activation { get; set; }
        public string Active_Base { get; set; }
        public string Recharge { get; set; }
        public string Usage { get; set; }
        public string pct { get; set; }
    }
}
