//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirtelSales.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_donotoussez_kpi_reseller
    {
        public int id { get; set; }
        public string Reseller_Code { get; set; }
        public string Reseller_Name { get; set; }
        public string SubDealer_Code { get; set; }
        public string Activation { get; set; }
        public string Active_Base { get; set; }
        public string Recharge { get; set; }
        public string Usage { get; set; }
        public string dist1 { get; set; }
        public string dist2 { get; set; }
    }
}
